### ISSUE TITLE
registry: package-scoped automation tokens for publishing

### ISSUE THREAD

**Issue by ethomson** [npm/roadmap#10]
**Summary**

As a followup to npm/roadmap#6, we will provide an option to limit the scope of automation tokens so that they can only publish specified packages.

**Intended Outcome**

Users can create an automation token that can publish only a single, specified package.

**How will it work?**

Much like an individual package can require two-factor authentication to be published, we will allow a package to allow only a limited set of automation tokens for its publication.

This allows you to create an individual automation token for an individual package.  That way if an automation token is ever leaked, the potential damage is limited to a single package.

**Questions**

* Should this token be scoped to a single package or be able to scope to a group of packages?

**Comment by MylesBorins** [comment]
We are continuing to scope this feature and will add it to the GitHub public roadmap when we the work is funded and we have a target date.
