### ISSUE TITLE
docs: open source docs.npmjs.com

### ISSUE THREAD

**Issue by ethomson** [npm/roadmap#17]
**Summary**

We will open source [docs.npmjs.com](https://docs.npmjs.com/) and allow community contributions.

**Intended Outcome**

* Users can clone the repository that contains the documentation and easily run a copy of the docs site
* Users can open issues that describe problems with the documentation
* Users can open pull requests that fix the documentation
* Pull requests will show a rendered version of the documentation

**Comment by MylesBorins** [comment]
**Update: April 19th 2021**

We are wrapping up the process to open source the docs, expecting to be ready soon.

**Comment by MylesBorins** [comment]
**Update: May 28th 2021**

The docs are now available at https://github.com/npm/documentation
