### ISSUE TITLE
website: show TypeScript information for packages that have type declarations

### ISSUE THREAD

**Issue by ethomson** [npm/roadmap#20]
**Summary**

Packages fall into one of three categories:

* They have TypeScript type information, and they contain `.d.ts` type declarations inside their package, and a `types` declaration in the `package.json`.  (These have "bundled type declarations".)
* They do not have TypeScript type information bundled, but the [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) project has created type declarations for them.  (These have "DefinitelyTyped type definitions").
* They have no TypeScript type declarations published.

For packages with bundled type declarations, we will decorate the package on the website to indicate that it has TypeScript type declarations bundled.  For packages with DefinitelyTyped type definitions, we will decorate the package on the website to indicate that it has TypeScript type declarations available in DefinitelyTyped, with a link to the package.

**Intended Outcome**

* Users can see that packages have great TypeScript support because they have types available
* Users get a link to the DefinitelyTyped package that provides type declarations

**Comment by MylesBorins** [comment]
We shipped an initial version of this feature!

https://github.blog/changelog/2020-12-16-npm-displays-packages-with-bundled-typescript-declarations/

Support for `.d.ts` and `DefinitelyTyped` will be coming as a follow up
