### ISSUE TITLE
registry: naming tokens

### ISSUE THREAD

**Issue by MylesBorins** [npm/roadmap#21]
**Summary**

Currently there is no ability to name generated tokens. Not being able to name tokens makes it harder to manage over time and audit existing tokens to ensure access is still necessary.

**Intended Outcome**

* Developers can name the tokens that they create on npmjs.com
* When viewing tokens developers should be able to see the names

**Outstanding Question**

* Should developers be able to rename tokens?

**How Will it Work**

TBD

**Comment by isaacs** [comment]
This sounds reasonable to me.  We already just manage these by talking to the registry and getting a JSON blob back, so it'd be pretty straightforward to add the `name` field in a backwards compatible way.

Write up an [RFC](https://github.com/npm/rfcs) proposing some syntax, and we can get it done with only the required amount of bikeshedding ;)

**Comment by MylesBorins** [comment]
We shipped this early this year 🎉
