### ISSUE TITLE
website: show TypeScript information for packages that have DefinitelyTyped type definitions

### ISSUE THREAD

**Issue by ethomson** [npm/roadmap#27]
**Summary**

Packages may not have bundled TypeScript type information, but someone may have done the hard work of creating the type declarations and publishing them to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped) .

For packages with DefinitelyTyped type definitions, we will decorate the package on the website to indicate that it has TypeScript type declarations available in DefinitelyTyped, with a link to the package.

**Intended Outcome**

* Users get a link to the DefinitelyTyped package that provides type declarations

**Comment by MylesBorins** [comment]
This feature is live!!!

https://github.blog/changelog/2021-01-25-npm-displays-links-to-definitelytyped-packages/
