### ISSUE TITLE
CLI: workspaces phase 2

### ISSUE THREAD

**Issue by MylesBorins** [npm/roadmap#30]
**Summary**

We initially launched support for workspaces in npm v7.0.0

While our initial implementation is a great start there is still a number of features that are needed to get workspaces in a place where they can be useful for day-to-day development of large projets.

**Intended Outcome**

* `npm workspaces` subcommand for managing workspaces
* Making various existing commands workspace aware

**References**

https://github.com/npm/rfcs/pull/273
https://github.com/npm/rfcs/pull/117

**Comment by MylesBorins** [comment]
**Update: April 19th 2021**

We've made excellent progress on workspaces but need to push into Q2 to consider this particular work item "launched".

**Comment by darcyclarke** [comment]
Closing: The last command to become workspace aware (ie. `npm diff`) shipped last week in [`v7.17.0`](https://github.com/npm/cli/releases/tag/v7.17.0)
