### ISSUE TITLE
website: Make the repo for a package more prominent

### ISSUE THREAD

**Issue by MylesBorins** [npm/roadmap#8]
**Summary**

Important data about a package such as the repo link + website link are not prominently featured on the website package page. Move this information to the top of the page could significantly improve discoverability

**Intended Outcome**

Developers visiting npmjs.com will be able to find important information quicker when visiting the landing page of a package.

**How Will it Work**

We will work with design to come up with a mock up and make changes to the templates for our website

**Stretch Goal**

There has been a request to add a GitHub icon to the npmjs.com website, if possible we should explore including this while we are doing this small design tweak

**References**
https://github.com/npm/feedback/discussions/50
https://github.com/npm/feedback/discussions/93

**Comment by NatashaDorfman** [comment]
https://github.com/npm/feedback/discussions/93 was implemented 
![Screen Shot 2021-07-18 at 14 06 12](https://user-images.githubusercontent.com/68326101/126064820-b223b22c-bb6f-4473-921d-9f5618f5f3b5.png)

**Comment by MylesBorins** [comment]
We've got both of these done now!

The Homepage and repository has been moved to the top of the side bar to make it more prominent and we now have a GitHub icon (and link) in the footer.

Great work team!
